### PR TITLE
Clean up errors coverage

### PR DESCRIPTION
**Pull request by swizzlr**
You made an arguably simple change, and the code coverage stuff I added earlier totally took the wind out of that. It would have been merged by now were it not for my contribution, so I'm putting my money where my mouth is and adding more tests to try to resolve the situation :)

### CODE REVIEW

**Comment by pmairoldi** [comment]
It's fine. Just let me know when it's ready to merge.

**Comment by swizzlr** [comment]
Seems that travis doesn't like running outside the context of host repo. You can merge this, since it should be an improvement; we also need to add tests verifying the nsError translation layer.

**Comment by pmairoldi** [comment]
Sounds good. I'll add tests for the nsError.

**Comment by swizzlr** [comment]
I'll get on it tomorrow if you don't have the time/patience, this is assuredly debt payback stuff, not fun!

**Pull request merged**
